# Generated by Django 5.2.5 on 2025-09-09 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_entries', '0002_character_characterassignment_folder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='folder',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='journal_entries.folder'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journals', to='journal_entries.folder'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('user', 'parent', 'name')},
        ),
    ]
